import { WeatherResponse } from "@/types/weather";

export const WEATHER_RESPONSE: WeatherResponse = {
    "queryCost": 4,
    "latitude": 40.4658,
    "longitude": -124.367,
    "resolvedAddress": "Capetown, Ferndale, CA, United States",
    "address": "CapeTown",
    "timezone": "America/Los_Angeles",
    "tzoffset": -7.0,
    "days": [
        {
            "datetime": "2025-04-08",
            "datetimeEpoch": 1744095600,
            "tempmax": 58.9,
            "tempmin": 44.1,
            "temp": 51.0,
            "feelslikemax": 58.9,
            "feelslikemin": 41.3,
            "feelslike": 49.8,
            "dew": 44.8,
            "humidity": 80.5,
            "precip": 0.0,
            "precipprob": 0.0,
            "precipcover": 0.0,
            "preciptype": null,
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 23.0,
            "windspeed": 9.2,
            "winddir": 149.8,
            "pressure": 1022.5,
            "cloudcover": 61.1,
            "visibility": 9.9,
            "solarradiation": 264.4,
            "solarenergy": 22.9,
            "uvindex": 9.0,
            "severerisk": 10.0,
            "sunrise": "06:49:11",
            "sunriseEpoch": 1744120151,
            "sunset": "19:49:55",
            "sunsetEpoch": 1744166995,
            "moonphase": 0.35,
            "conditions": "Partially cloudy",
            "description": "Partly cloudy throughout the day.",
            "icon": "partly-cloudy-day",
            "stations": [
                "PTEC1",
                "KACV"
            ],
            "source": "obs"
        },
        {
            "datetime": "2025-04-09",
            "datetimeEpoch": 1744182000,
            "tempmax": 58.9,
            "tempmin": 40.9,
            "temp": 50.1,
            "feelslikemax": 58.9,
            "feelslikemin": 39.0,
            "feelslike": 49.8,
            "dew": 46.1,
            "humidity": 86.9,
            "precip": 0.0,
            "precipprob": 0.0,
            "precipcover": 0.0,
            "preciptype": null,
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 10.3,
            "windspeed": 12.8,
            "winddir": 318.2,
            "pressure": 1023.2,
            "cloudcover": 0.0,
            "visibility": 9.8,
            "solarradiation": 296.1,
            "solarenergy": 25.5,
            "uvindex": 9.0,
            "severerisk": 10.0,
            "sunrise": "06:47:36",
            "sunriseEpoch": 1744206456,
            "sunset": "19:50:57",
            "sunsetEpoch": 1744253457,
            "moonphase": 0.39,
            "conditions": "Clear",
            "description": "Clear conditions throughout the day.",
            "icon": "clear-day",
            "stations": [
                "PTEC1",
                "KFOT",
                "KACV"
            ],
            "source": "obs"
        },
        {
            "datetime": "2025-04-10",
            "datetimeEpoch": 1744268400,
            "tempmax": 65.8,
            "tempmin": 44.1,
            "temp": 53.5,
            "feelslikemax": 65.8,
            "feelslikemin": 41.6,
            "feelslike": 52.8,
            "dew": 49.3,
            "humidity": 87.2,
            "precip": 0.02,
            "precipprob": 100.0,
            "precipcover": 4.17,
            "preciptype": [
                "rain"
            ],
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 17.2,
            "windspeed": 13.3,
            "winddir": 126.0,
            "pressure": 1024.0,
            "cloudcover": 51.3,
            "visibility": 7.9,
            "solarradiation": 250.7,
            "solarenergy": 21.6,
            "uvindex": 8.0,
            "severerisk": 10.0,
            "sunrise": "06:46:02",
            "sunriseEpoch": 1744292762,
            "sunset": "19:51:59",
            "sunsetEpoch": 1744339919,
            "moonphase": 0.42,
            "conditions": "Rain, Partially cloudy",
            "description": "Partly cloudy throughout the day with afternoon rain.",
            "icon": "rain",
            "stations": [
                "PTEC1",
                "KFOT",
                "KACV",
                "remote"
            ],
            "source": "obs"
        },
        {
            "datetime": "2025-04-11",
            "datetimeEpoch": 1744354800,
            "tempmax": 51.0,
            "tempmin": 44.0,
            "temp": 47.0,
            "feelslikemax": 51.0,
            "feelslikemin": 35.1,
            "feelslike": 40.8,
            "dew": 43.2,
            "humidity": 86.6,
            "precip": 0.048,
            "precipprob": 5.0,
            "precipcover": 16.67,
            "preciptype": [
                "rain"
            ],
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 36.9,
            "windspeed": 23.0,
            "winddir": 3.4,
            "pressure": 1023.5,
            "cloudcover": 87.4,
            "visibility": 4.1,
            "solarradiation": 99.4,
            "solarenergy": 8.6,
            "uvindex": 3.0,
            "severerisk": 10.0,
            "sunrise": "06:44:29",
            "sunriseEpoch": 1744379069,
            "sunset": "19:53:02",
            "sunsetEpoch": 1744426382,
            "moonphase": 0.46,
            "conditions": "Partially cloudy",
            "description": "Partly cloudy throughout the day.",
            "icon": "partly-cloudy-day",
            "stations": null,
            "source": "fcst"
        },
        {
            "datetime": "2025-04-12",
            "datetimeEpoch": 1744441200,
            "tempmax": 51.0,
            "tempmin": 43.1,
            "temp": 46.6,
            "feelslikemax": 51.0,
            "feelslikemin": 33.4,
            "feelslike": 39.2,
            "dew": 38.5,
            "humidity": 73.5,
            "precip": 0.032,
            "precipprob": 0.0,
            "precipcover": 12.5,
            "preciptype": [
                "rain"
            ],
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 42.5,
            "windspeed": 26.4,
            "winddir": 358.3,
            "pressure": 1021.5,
            "cloudcover": 28.6,
            "visibility": 10.1,
            "solarradiation": 256.0,
            "solarenergy": 22.1,
            "uvindex": 7.0,
            "severerisk": 10.0,
            "sunrise": "06:42:56",
            "sunriseEpoch": 1744465376,
            "sunset": "19:54:04",
            "sunsetEpoch": 1744512844,
            "moonphase": 0.5,
            "conditions": "Partially cloudy",
            "description": "Partly cloudy throughout the day.",
            "icon": "partly-cloudy-day",
            "stations": null,
            "source": "fcst"
        },
        {
            "datetime": "2025-04-13",
            "datetimeEpoch": 1744527600,
            "tempmax": 58.9,
            "tempmin": 45.0,
            "temp": 51.3,
            "feelslikemax": 58.9,
            "feelslikemin": 37.5,
            "feelslike": 48.3,
            "dew": 39.7,
            "humidity": 64.8,
            "precip": 0.0,
            "precipprob": 0.0,
            "precipcover": 0.0,
            "preciptype": [
                "rain"
            ],
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 36.5,
            "windspeed": 23.5,
            "winddir": 3.8,
            "pressure": 1017.5,
            "cloudcover": 6.8,
            "visibility": 10.1,
            "solarradiation": 293.9,
            "solarenergy": 25.4,
            "uvindex": 9.0,
            "severerisk": 10.0,
            "sunrise": "06:41:24",
            "sunriseEpoch": 1744551684,
            "sunset": "19:55:06",
            "sunsetEpoch": 1744599306,
            "moonphase": 0.53,
            "conditions": "Clear",
            "description": "Clear conditions throughout the day.",
            "icon": "clear-day",
            "stations": null,
            "source": "fcst"
        },
        {
            "datetime": "2025-04-14",
            "datetimeEpoch": 1744614000,
            "tempmax": 57.3,
            "tempmin": 48.8,
            "temp": 52.3,
            "feelslikemax": 57.3,
            "feelslikemin": 44.3,
            "feelslike": 50.6,
            "dew": 44.0,
            "humidity": 73.5,
            "precip": 0.276,
            "precipprob": 1.0,
            "precipcover": 4.17,
            "preciptype": [
                "rain"
            ],
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 22.4,
            "windspeed": 12.5,
            "winddir": 352.3,
            "pressure": 1016.2,
            "cloudcover": 26.7,
            "visibility": 14.2,
            "solarradiation": 268.9,
            "solarenergy": 23.1,
            "uvindex": 8.0,
            "severerisk": 10.0,
            "sunrise": "06:39:52",
            "sunriseEpoch": 1744637992,
            "sunset": "19:56:08",
            "sunsetEpoch": 1744685768,
            "moonphase": 0.56,
            "conditions": "Partially cloudy",
            "description": "Partly cloudy throughout the day.",
            "icon": "partly-cloudy-day",
            "stations": null,
            "source": "fcst"
        }
    ],
    "stations": {
        "PG249": {
            "distance": 9366.0,
            "latitude": 40.487,
            "longitude": -124.26,
            "useCount": 0,
            "id": "PG249",
            "name": "Upper Bear River Road CA US PGE",
            "quality": 0,
            "contribution": 0.0
        },
        "PTEC1": {
            "distance": 24793.0,
            "latitude": 40.257,
            "longitude": -124.266,
            "useCount": 0,
            "id": "PTEC1",
            "name": "COOSKIE MOUNTAIN CA US",
            "quality": 0,
            "contribution": 0.0
        },
        "KACV": {
            "distance": 61513.0,
            "latitude": 40.98,
            "longitude": -124.1,
            "useCount": 0,
            "id": "KACV",
            "name": "KACV",
            "quality": 100,
            "contribution": 0.0
        },
        "PG287": {
            "distance": 19989.0,
            "latitude": 40.469,
            "longitude": -124.131,
            "useCount": 0,
            "id": "PG287",
            "name": "Monument Road CA US PGE",
            "quality": 0,
            "contribution": 0.0
        },
        "KFOT": {
            "distance": 21695.0,
            "latitude": 40.54,
            "longitude": -124.13,
            "useCount": 0,
            "id": "KFOT",
            "name": "KFOT",
            "quality": 90,
            "contribution": 0.0
        },
        "PG895": {
            "distance": 19413.0,
            "latitude": 40.546,
            "longitude": -124.163,
            "useCount": 0,
            "id": "PG895",
            "name": "Price Creek CA US PGE",
            "quality": 0,
            "contribution": 0.0
        }
    },
    "currentConditions": {
        "datetime": "23:40:00",
        "datetimeEpoch": 1744353600,
        "temp": 51.6,
        "feelslike": 51.6,
        "humidity": 99.6,
        "dew": 51.5,
        "precip": 0.0,
        "precipprob": 0.0,
        "snow": 0.0,
        "snowdepth": 0.0,
        "preciptype": null,
        "windgust": 6.6,
        "windspeed": 5.1,
        "winddir": 7.0,
        "pressure": 1025.0,
        "visibility": 0.0,
        "cloudcover": 100.0,
        "solarradiation": 0.0,
        "solarenergy": 0.0,
        "uvindex": 0.0,
        "conditions": "Overcast",
        "icon": "cloudy",
        "stations": [
            "PG287",
            "KFOT",
            "PG895",
            "PG249"
        ],
        "source": "obs",
        "sunrise": "06:44:29",
        "sunriseEpoch": 1744379069,
        "sunset": "19:53:02",
        "sunsetEpoch": 1744426382,
        "moonphase": 0.46
    }
    
};
